### PR TITLE
Hera module changes related to contrib packages

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
Issue #109.
Also changes the cmake module from 3.9.0 to 3.16.1.

### CODE REVIEW

**Comment by climbfuji** [comment]
Looks good to me.

**Comment by binli2337** [comment]
Looks good to me. I will update the module files.

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA <https://github.com/MinsukJi-NOAA> are you going to run RT
on hera to confirm it is working?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA <https://github.com/MinsukJi-NOAA> are you going to run RT on hera to confirm it is working?

It's running right now.  I will attach the results when ready.

**Comment by junwang-noaa** [comment]
Thank you, Minsuk!

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]
All good

**Comment by junwang-noaa** [comment]
Denise, can you merge the PR then? Thanks

**Pull request merged**
