### PR TITLE
Add 1 day reg test that matches a benchmark case

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
* A 1 day regression test (1 day run and cold start)  for the IC 2013040100 with the same physics/ICs/set-up as the benchmarks was added.  2013040100 was chosen as it frequently was the most unstable IC for previous bugs and will hopefully help us catch bugs in the future.
* The date suite runs now have 4 more tests for 2013 cases (these are not run as part of the standard regression tests but can be turned on for quick-easy testing of 8 IC for stability testing).
* Several app level files were updated to match the latest of the ufs-weather-model 
* NEMS was updated to the most recent develop branch

This PR closes issue #46

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Jun has asked that we update to the latest post libraries so they can remove the older ones. I see you have an update for conf/fv3 on dell, but can we update fv3_coupled conf files with this commit also? We want post/8.0.6

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen  yes, we can update all the post libraries on this commit. 

In addition we will be updating to use the latest fv3atm from PR https://github.com/NOAA-EMC/fv3atm/pull/81

**Comment by junwang-noaa** [comment]
Jessica,

I thought we will have a clean s2s commit with Moorthi's changes which is
in current fv3atm (PR#77 and PR#44) with wave test added, then we
willcommit Shan's  fraction grid change to s2s, is the plan changed?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa   If we do that, then this PR needs to go in without updating to fv3atm to NOAA-EMC/fv3atm#81 and then I need to debug the WW3 build so that the WW3 test can be added here with this current fv3atm.

**Comment by junwang-noaa** [comment]
That is my understanding. So we have:
1) fv3atm PR#44 and #77 with atm<-> wave coupling,  in s2s we will have
with atm<->wav coupling, and fv3-mom6-cice5-wav enabled
2) fv3atm PR #81 with fraction grid changes and CCPP updates, in s2s we
will have no baseline results change but have ccpp tests added

I understand that we need a 1 day benchmark test in 2). But I do hope we
get 1) done first. If you'd like to change the plan, please let Bin/Denise
know. Bin supposed to work on merge #81 to s2s, do you want that to be in
your PR?  Then we have to resolve this 1 day test difference issue.

**Comment by JessicaMeixner-NOAA** [comment]
I'm closing this commit since PR #60 will break this... I'll make a new PR with an updated baseline. @DeniseWorthen since I have to make an updated baseline (it's made, just need to move it to a "develop-YYYYMMDD" from it's current "update-20200321" spot.  Do you want me to add any of the rearrangements that will be needed in upcoming PRs or just go with how it is now?

**Comment by DeniseWorthen** [comment]
Don't make extra work for yourself. I'll do it when I commit the cmeps and restart tests.

**Pull request closed without merging**
