### PR TITLE
Add debug compilation flag specification at top level

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
Resolves issue #16 
1. Debug flags are specified in coupledFV3_MOM6_CICE_debug.appBuilder
2. Flags are used by NEMS MOM6 and CICE submodules to initiate debug makes
3. All regression tests passed

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
Attach build log with and without debug flags. Also attach regression test report.

[build_w_debug.log](https://github.com/ufs-community/ufs-s2s-model/files/4078137/build_w_debug.log)
[build_wo_debug.log](https://github.com/ufs-community/ufs-s2s-model/files/4078138/build_wo_debug.log)
[rtreport.txt](https://github.com/ufs-community/ufs-s2s-model/files/4078139/rtreport.txt)

**Comment by DeniseWorthen** [comment]
We also need to update two files in conf for adding the -link_mpi=dbg to the FFLAGS_DEBUG settings for the configure.fv3_coupled.cheyenne.intel and configure.fv3_coupled.hera.intel.  These have not yet been added to the develop branch but should be.

**Comment by DeniseWorthen** [comment]
I've confirmed the top-level app build passes the flags down to MOM6 and CICE5. Once we merge the related PRs to the develop branches of CICE, MOM6-interface and NEMS, you'll need to amend you PR to point to NOAA_EMC repos (instead of your forks) and we can approve. Thanks!

**Review by DeniseWorthen — APPROVED** [review]
Looks good.

**Review by binli2337 — APPROVED** [review]

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
