### PR TITLE
Update NEMS,FV3,CICE

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Updates for issue #27:

*Mediator-calculated fluxes in icy water are not used when running FV3 coupled
*FV3 is updated to import fields from CICE using CICE field names; the custom merge in the mediator phase prep_atm is no longer required and is removed
*Field names for SW fields exported by CICE  have been changed and corresponding changes have been made in the mediator
*Use of Atm-Ocn fields on the Atm grid are commented out in mediator phase prep_atm since they are not used
*When diagnostic field dumping is enabled, both FV3 and NEMS write Atm fields on the native tile grid
*The NEMS EARTH_GRID_COMP is capable of building a second mediator (CMEPS).

### CODE REVIEW

**Review by binli2337 — APPROVED** [review]
The changes look good to me.

**Comment by junwang-noaa** [comment]
Denise,

May I ask if the capability of writing out atm field on the native tile
grid is tested? I assume you are running fv3 and mediator with same tasks?
Does this add requirement of mediator to use multiple of 6 for number of
the pets  if mediator and atm are not running on the same tasks. Thanks.

**Comment by DeniseWorthen** [comment]
Jun--we do run with the mediator and atm on the same tasks (multiple of 6). I suspect you are right that this requires that we run on multiples of 6 for the mediator regardless of whether it is sharing w/ atm but only if the diagnostic field dumping was enabled.

For s2s, I did verify that the fields "to/from atm" and "from/to med" are the same when field dumping is enabled. The only issue is lining up the time-slices.

**Comment by junwang-noaa** [comment]
Thanks, that is great. I think the time slices are depending on when you
put the code of outputting those fields.  FV3 has time checker for import
fields, so at least the field passing is not a problem.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
