### PR TITLE
added ccpp to the coupled system

### PR DESCRIPTION
**Pull request by panll**
adding CCPP to th coupled system, the files added/modified include:
coupledFV3_CCPP_MOM6_CICE.appBuilder
compsets/all_ccpp.input
compsets/cpld_fv3_ccpp_mom6_cice_2d_atm_flux.input
compsets/cpld_fv3_ccpp_mom6_cice_cold_atm_flux.input
compsets/fv3mom6cice5_ccpp.input
parm/input.mom6_ccpp.nml.IN

suite file suite_FV3_GFS_2017_couple.xml  under ccpp/suite is also needed.
following files need to be updated too:
ccpp/physics/physics/GFS_surface_generic.F90, 
ccpp/physics/physics/GFS_PBL_generic.F90
ccpp/physics/physics/sfc_sice.f

### CODE REVIEW

**Comment by climbfuji** [comment]
Note: The changes in ccpp-physics to master will be committed with PR https://github.com/NCAR/ccpp-physics/pull/372. The suite definition file ccpp/suites/suite_FV3_GFS_2017_coupled.xml will be committed with PR https://github.com/NOAA-EMC/fv3atm/pull/30. Both PRs are part of https://github.com/ufs-community/ufs-weather-model/pull/18, which is currently scheduled for Monday Jan 6.

**Comment by panll** [comment]
The changes for fv3atm part for adding CCPP in s2s have been merged to the NOAA-EMC/fv3atm. I updated the s2s part changes and tested. The codes are ready to merge.

There are two issues we need to pay attention for testing:
1) the post file FV3/io/post_gfs.F90 needs to be updated (this is not related to CCPP)
2) the fv3atm needs to be synchronized with latest version after checking out, e.g.:
    git checkout develop
    git submodule sync
    git submodule update --init --recursive

**Comment by climbfuji** [comment]
This PR has been merged into https://github.com/ufs-community/ufs-s2s-model/pull/64. It should remain open and will be flagged as merged automatically when https://github.com/ufs-community/ufs-s2s-model/pull/64 is merged.

**Comment by DeniseWorthen** [comment]
This PR was superceded by PR #64.

**Pull request closed without merging**
