### PR TITLE
add CCPP options for wcoss-phase2 configure

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
I apologize, I missed this in my earlier diffs between what I was testing and what was in this branch, but this is needed to successfully run on wcoss-phase2.

**Comment by junwang-noaa** [comment]
Thanks, I was a little confused how model can run on phase2 without these
changes.

**Comment by junwang-noaa** [comment]
@DeniseWorthen
<https://github.com/ufs-community/ufs-s2s-model/commits?author=DeniseWorthen>
after this code commit to the branch, would you please delete the tag and
make a new tag: s2s_prototype4.0_wcoss2? Thanks

**Comment by DeniseWorthen** [comment]
The tag is made.

**Pull request merged**
