### PR TITLE
fv3atm update: CCPP tendencies bugfixes, global restart reproducibility, halo boundary update in dycore, transition to cap_gen.py part 1

### PR DESCRIPTION
**Pull request by climbfuji**
### Description of changes

- Update .gitmodules and submodule pointer for stochastic_physics, fv3atm and NEMS for code review and testing changes described in https://github.com/ufs-community/ufs-weather-model/pull/208 and associated PRs.
    - Note that the NEMS code is currently an open PR (https://github.com/NOAA-EMC/NEMS/pull/82) that needs to be merged first, while the fv3atm and stochastic_physics are updates to point to the head of the original branches.
- Change `-DOPENMP` to `-D_OPENMP` to match the changes made in fv3atm

### Specific notes

Are changes expected to change answers?
- expect changes for GSL physics, regional runs, and restart runs (global and regional)

Testing performed:
- somebody needs to run the s2s tests for this change

### CODE REVIEW

**Comment by climbfuji** [comment]
@BinLiu-NOAA @junwang-noaa could some one please run the regression tests for this PR before we merge fv3atm? Thank you ...

**Comment by junwang-noaa** [comment]
I think it is for  Bin Li @binli2337.

**Comment by climbfuji** [comment]
@BinLiu-NOAA @junwang-noaa this PR is ready from my side, I don't have the regression test logs yet, though

**Comment by junwang-noaa** [comment]
Dom, this PR will be after Shan's fractional grid PR.

**Comment by climbfuji** [comment]
> Dom, this PR will be after Shan's fractional grid PR.
> […](#)

Sure, no problem. As long as we don't have to wait with ufs-weather-model to proceed, that's fine.

**Comment by climbfuji** [comment]
@junwang-noaa I saw you asked @shansun6 to update fv3atm to my Sep 26 commit in fv3atm (hash 9e1ba7). Then this PR here will no longer be required.

**Comment by junwang-noaa** [comment]
Dom, Shan's branch is updated to current s2s fv3 version 9e1ba7 (PR#157,
RRTMGP), not  ab0e5ae3 in this PR. SInce we don't want to change current
s2s baseline, just add a new fractional grid test to have a clean
comparison of the new fractional grid test with the current non-fractional
grid test. We still need this PR #200, we will create a new set of baseline
for PR #200 due to results change.

**Comment by climbfuji** [comment]
> Dom, Shan's branch is updated to current s2s fv3 version 9e1ba7 (PR#157, RRTMGP), not ab0e5ae3 in this PR. SInce we don't want to change current s2s baseline, just add a new fractional grid test to have a clean comparison of the new fractional grid test with the current non-fractional grid test. We still need this PR #200, we will create a new set of baseline for PR #200 due to results change.
> […](#)

Got it, thanks.

**Comment by ShanSunNOAA** [comment]
Hi Jun,

I have added the log files from the exiting regression test
cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt
which passed the regression test, and the same test using the fractional
grid
cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt_frac

The run dir is at /scratch2/BMC/gsd-fv3-dev/Shan.Sun/S2S_RT/rt_25890/.
Please let me know if you have any questions.

Thanks,
Shan

**Comment by binli2337** [comment]
@climbfuji   I will run the regression tests on Hera, Orion and Dell 3 after the code is updated.

**Comment by binli2337** [comment]
@climbfuji  @junwang-noaa 
The thread test "cpld_fv3_ccpp_mom6_cice_cmeps_2d_2threads" failed. 

Error message:
  1: An error occurred in ccpp_physics_init
  1: An error occured in GFS_phys_time_vary_init: Logic error: nthrds does not match size of Interstitial variable
  1:
  1: FATAL from PE     1: Call to CCPP physics_init step failed
  1:
  1: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

**Comment by climbfuji** [comment]
> @climbfuji @junwang-noaa
> The thread test "cpld_fv3_ccpp_mom6_cice_cmeps_2d_2threads" failed.
> 
> Error message:
> 1: An error occurred in ccpp_physics_init
> 1: An error occured in GFS_phys_time_vary_init: Logic error: nthrds does not match size of Interstitial variable
> 1:
> 1: FATAL from PE 1: Call to CCPP physics_init step failed
> 1:
> 1: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

@binli2337 I just heard from @SMoorthi-emc about this issue. Do you have a test case on hera (or instructions) so that I can reproduce the error? Thanks!

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Pull request merged**
