### PR TITLE
Update FV3, NEMS

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Resolves issue #20 
New baseline is added for Hera; logs are committed

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Can we point to "master-20200128" on the wcoss.input even though the baselines aren't there (yet)? 

My only other comment is if possible put more detail in the commit message when you merge so we don't have to go to the issue to see the details of what the updates were since this was a big update for fv3 and NEMS.   --- and to add that this update for MOM6 did not change answers but  added the variable to the restart file.

**Comment by DeniseWorthen** [comment]
Yes, thanks. I've updated wcoss.input and will include details of the recent FV3, NEMS and MOM6 commit when I merge.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]
Looks good to me. Please prepare a detailed merge message.

**Comment by junwang-noaa** [comment]
Denise,

I want to confirm that you have the latest FV3 revision and the NEMS commit
with the unmerged field. So after this merge the code is ready for
prototype 3.1. Thanks.

Jun

**Comment by DeniseWorthen** [comment]
Yes Jun, we are now up-to-date with FV3 and the NEMS change with the un-merged fields in prep_atm. Thanks.

**Pull request merged**
