### PR TITLE
update ufs-s2s-model to use updated FV3 and FMS tag 2019.01

### LINKED ISSUE #38: Test updated FV3 associated with pull request #44 in s2s system
After the ufs-s2s-model is updated with new FV3 (with atmosphere-wave coupling updates), the following tests will be done:
1. Generate 6 new baselines.
2. Run the ufs-s2s-model for 5 days starting from Jan 1, Apr 1, Jul 1 and Oct 1 of 2012.
3. Run the ufs-s2s-model for 35 days starting from Jan 1, 2013.

### PR DESCRIPTION
**Pull request by binli2337**
This is ufs-s2s-model commit to merge Moorthi's ccpp and atm-wave coupling code changes in fv3.

closes #38

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@junwang-noaa 

This commit retains the setting of value 'huge' over land for fields set to ocean (dusfc etc) in the physics driver. Is that what we want to do?

**Comment by junwang-noaa** [comment]
> @junwang-noaa
> 
> This commit retains the setting of value 'huge' over land for fields set to ocean (dusfc etc) in the physics driver. Is that what we want to do?

I think it's good to have this until we have land or lake models in the coupled system. Besides it sets "huge" over lake points too besides land.

**Comment by junwang-noaa** [comment]
Bin,

I want to follow up with the tests specified in PR #38, they have been done
and the results are reasonable,  correct?

**Comment by binli2337** [comment]
Jun,

The tests mentioned in issue #38 have been done and the results are reasonable.

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
