### PR TITLE
Update .gitmodules and submodule pointer for fv3atm for PR #157 (RRTMG cloud overlap method update)

### PR DESCRIPTION
**Pull request by climbfuji**
### Description of changes

Update `.gitmodules` and submodule pointer for fv3atm for code review and testing the changes described in https://github.com/NOAA-EMC/fv3atm/pull/157 and https://github.com/NCAR/ccpp-physics/pull/487.

### Specific notes

Are changes expected to change answers?
- no, unless you are using the suite definition file `FV3/ccpp/suites/suite_FV3_RRFS_v1beta.xml` in one of your tests

Testing performed: none. I need someone to help me testing these changes.

For the corresponding ufs-weather-model PR and all associated PRs, see https://github.com/ufs-community/ufs-weather-model/pull/184.

### CODE REVIEW

**Comment by climbfuji** [comment]
@junwang-noaa Please see here for the s2s model PR corresponding to https://github.com/ufs-community/ufs-weather-model/pull/184.

**Comment by binli2337** [comment]
Regression tests have been run on Hera, Orion and Dell 3. The log files are at /scratch1/NCEPDEV/nems/Bin.Li/S2S/test/ufs-s2s-model/tests.

**Comment by junwang-noaa** [comment]
@climbfuji would you please commit the log files to your branch?

**Comment by climbfuji** [comment]
@binli2337 conducted regression tests on hera.intel, orion.intel, wcoss_dell_p3. All tests passed regression test logs updated in the PR.

**Comment by climbfuji** [comment]
Thanks, @binli2337  for running the tests. Once we merged fv3atm, I will update the submodule pointer here and make sure that the code is identical between my branch that you used for testing and the new head of fv3atm develop.

**Review by binli2337 — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
Thanks to Bin who ran all the RT tests!

**Pull request merged**
