### PR TITLE
cice6 debug compile

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
This PR addresses Issue #132

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Thanks for making the code changes. Is the cic6 clean up step also working?

**Comment by MinsukJi-NOAA** [comment]
Yes. compile.sh defaults to 'yes' for clean_before and clean_after, and no errors occurred.

**Review by junwang-noaa — COMMENTED** [review]
May I ask why we remove the tests/compile.sh? I see we still use compile.sh in rt.sh, isn't it?

        ./compile.sh $PATHTR/FV3 $MACHINE_ID "${NEMS_VER}" $COMPILE_NR > ${LOG_DIR}/compile_${COMPILE_NR}.log 2>&1

**Comment by MinsukJi-NOAA** [comment]
> May I ask why we remove the tests/compile.sh? I see we still use compile.sh in rt.sh, isn't it?
> 

This commit removes the CICE6_MAKEOPT flag in compile.sh since CICE6 uses CICE_MAKEOPT.

**Comment by DeniseWorthen** [comment]
I've tested on both orion and hera; both compiles appear correct for debug=y setting. 

I added an issue to CICE to add the the link_mpi=debug flags to the macros.

**Review by DeniseWorthen — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Pull request merged**
