### PR TITLE
Convert 2 remaining ccpp prod tests (debug cold and warm) to rt.sh

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
Issue #85. Debug tests have been tested on Hera so far.

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen @junwang-noaa 
On Hera, esmf8.0.0g is used instead of esmf8.0.0 for debug build.
On Orion, which module version can be used instead of esmf8.0.0.para for debug?

**Comment by DeniseWorthen** [comment]
It looks like a debug module needs to be built on orion.

**Comment by junwang-noaa** [comment]
George built esmf800 on Orion. Is esmf800g required for the debug mode test?

**Comment by DeniseWorthen** [comment]
Yes, because the caps and the mediator are then built with debug flag settings also.

**Comment by MinsukJi-NOAA** [comment]
George built esmf800g on Orion. It is loaded by `module load esmflocal/8_0_0.g`

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
Great work, @MinsukJi-NOAA !

**Comment by MinsukJi-NOAA** [comment]
> Great work, @MinsukJi-NOAA !

Thanks, Dom!

**Comment by MinsukJi-NOAA** [comment]
Related PR's are https://github.com/NOAA-EMC/NEMS/pull/57 and https://github.com/NOAA-EMC/NEMS/pull/60. These two are combined to https://github.com/NOAA-EMC/NEMS/pull/61

**Comment by MinsukJi-NOAA** [comment]
S2S RT successfully passed on Orion with https://github.com/NOAA-EMC/NEMS/pull/61 change

**Comment by MinsukJi-NOAA** [comment]
S2S RT successfully passed on Hera

**Comment by MinsukJi-NOAA** [comment]
OK, this is good to go.

**Pull request merged**
