### PR TITLE
Bugfix/wave1dtest

### PR DESCRIPTION
**Pull request by DeniseWorthen**
### Description of changes

Sets correct MOM_input template for 1d bmark wave test

### Specific notes

Issues Fixed (include github issue #):

Bug fix for issue #192 

Are changes expected to change answers?
- bit for bit: no
 new baseline for this test will be generated and will replace existing test files in develop-20200921 

Specific changes:
- changes in parm directory (no)
- changes in module files (no)
- new tests added or removed (no): bug fix in cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt

Testing performed:
- machines: new baseline for single test will be generated on hera,orion and dell-p3
- details:

Hashes used for testing:
- NEMS:9d05172
- CMEPS:5e63bd
- FV3:9e1ba7c7
- MOM6:3ce81f4
- CICE:285985c
- WW3:96e3f3a
- FMS:f61416fe
- stochastic_physics:ffdd19b

Co-authored by:

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Ready for review. 

A new baseline for this test has been created on all platforms with temporary name "new_RT-Baselines_1d_bmwav_ccpp_cmeps". Once this PR has been merged, I will rename the test baseline on all platforms.

**Comment by DeniseWorthen** [comment]
How do we want to go about merging this PR? I've merged the latest develop. I can run the RTs using the  ``new_RT-Baselines_1d_bmwav_ccpp_cmeps`` to compare against; they should reproduce. Once we've merged the PR I'll have to change both the directory name in the baseline as well as the ``CNTL_DIR`` in the test itself.

**Comment by junwang-noaa** [comment]
I think that will work. First run RT against new_RT-Baselines_1d_bmwav_ccpp_cmeps. If that reproduces, then copy to new baseline and run final RT.

**Comment by DeniseWorthen** [comment]
Just to be sure, when you say 'copy to new baseline':  I'll only be replacing the values of the existing ``RT-Baselines_1d_bmwav_ccpp_cmeps`` in the 0921 baseline. Once I do that, I can run all the RTs against the entire baseline.

**Comment by junwang-noaa** [comment]
Yes, that is what I mean. Sp in the new baseline, all the other tests will
be copied from the current  0921 baseline, but the test
RT-Baselines_1d_bmwav_ccpp_cmeps was created from your branch in the PR.

**Comment by DeniseWorthen** [comment]
OK, so we'll have a new 0928 baseline with the single test fixed.

**Comment by DeniseWorthen** [comment]
All logs added. Ready for review and merge.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
@DeniseWorthen the changes look good.  Thank you so much for catching and fixing this bug!

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
