### PR TITLE
WIP: cmake build in ufs-s2s

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**

This PR is a first in a series of pull requests targeted towards building the UFS-s2s-model with cmake.
In this PR:
- CMakeLists.txt is introduced at the root level of the application.
- MOM6 and CICE6 are introduced via an interface.
- MOM6 submodule (MOM6-interface) is deprecated.  MOM6 (model) source code is a submodule of the sub-directory MOM6-interface.
- CICE6 is introduced as a submodule under sub-directory CICE-interface.

**Impact**
Zero diff is expected as a result of this merge.

**Testing**
@MinsukJi-NOAA compiled and ran regression tests with the dependencies below.
The result was zero-diff.

**Dependencies**
- A change is necessary in the NEMS repository to correctly point to the MOM6 source code.  This change is captured in [this](https://github.com/MinsukJi-NOAA/NEMS/tree/feature/s2s-cmake-target) NEMS branch and PR #[72](https://github.com/NOAA-EMC/NEMS/pull/72).

**Upcoming**
The next series of PR's will bring in cmake functionality in additional components e.g. NEMS, CMEPS, etc.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Do we want to bring this into ufs-s2s prior to switching over to CICE6?

**Comment by junwang-noaa** [comment]
I think we can get this committed as cmake only works for CICE6.

**Comment by aerorahul** [comment]
> Do we want to bring this into ufs-s2s prior to switching over to CICE6?

@DeniseWorthen 
It doesn't make a difference as of now. we have not *hooked* up CICE6 into ufs-s2s in the CMake build. As in, we are not linking the CICE6 library into S2S. It is just a placeholder. 

If there are active developers working on the hook-up of CICE6 through the GNUMake, I think it would be good to have the same umbrella repo to do that development on.

**Comment by MinsukJi-NOAA** [comment]
As @aerorahul stated, this commit did not affect the current compile.sh way of building and rt.sh way of testing (on Hera).

**Comment by DeniseWorthen** [comment]
I understand all of this---but my concern is that as soon as it appears in ufs-s2s, you're going to have people asking how to build, how to run regression tests etc.

**Comment by aerorahul** [comment]
> I understand all of this---but my concern is that as soon as it appears in ufs-s2s, you're going to have people asking how to build, how to run regression tests etc.

By 'it' you are referring to CICE6 I assume.
If that is your fear, we can comment out the CICE6 submodule and all they get is a directory `CICE-interface` with 2 files that mean nothing, because I put a big, fat `FATAL_ERROR` for cmake build in ufs-s2s.

Does that work for you?

**Comment by DeniseWorthen** [comment]
I just feel we're jumping the gun on this. We have a S2S-commit plan for a whole series of major changes---CMEPS brought in, NEMS dropped. CICE6 brought in, CICE5 dropped. Fractional grid tested etc. I don't really see the advantage of bringing the cmake build in right at this stage. What advantage does it provide at this stage, since we're not using CICE6?

**Comment by aerorahul** [comment]
> I just feel we're jumping the gun on this. We have a S2S-commit plan for a whole series of major changes---CMEPS brought in, NEMS dropped. CICE6 brought in, CICE5 dropped. Fractional grid tested etc. I don't really see the advantage of bringing the cmake build in right at this stage. What advantage does it provide at this stage, since we're not using CICE6?

I don't see how this commit is disrupting or jumping any of those plans. This is complementary development.
We are bringing in files that will make transition to cmake as your development proceeds.

Besides, the JEDI DA infrastructure requires access to the libraries of the model components and its dependencies in exact order. With GNUMake, we will have to hard-wire every single library and in right order. As you change the order, we will have to change the order.  This is a nightmare.

If we have to wait for all the items you listed, I am looking at at least a year before we can do anything.

**Comment by DusanJovic-NOAA** [comment]
Is there a way to test this?

**Comment by aerorahul** [comment]
> Is there a way to test this?

Right now, libraries are created.  We haven't managed to create an executable.

This PR is no longer in consideration, and will be closed.

**Comment by aerorahul** [comment]
Taking alternate route.
closing.

**Pull request closed without merging**
