### PR TITLE
update MOM6 to point to EMC 20200913 commit which corresponding to GFDL 20200909 commit

### PR DESCRIPTION
**Pull request by jiandewang**
### Description of changes
update EMC MOM6 to GFDL 20200909 commit (dev-master-candidate-NCAR-2020-08-11)
### Specific notes

Issues Fixed (include github issue #):
Issue #180 
[hera-log.pdf](https://github.com/ufs-community/ufs-s2s-model/files/5222393/hera-log.pdf)
[Orion-log.pdf](https://github.com/ufs-community/ufs-s2s-model/files/5222397/Orion-log.pdf)

Are changes expected to change answers?
- bit for bit (yes)

Specific changes:
- changes in parm directory (no)
- changes in module files (no)
- new tests added or removed (no)

Testing performed:
- machines: orion, hera and Dell-p3
- details: no answer change, see attached run log

Hashes used for testing:
- NEMS: 9d05172b
- CMEPS: 5e63bd4d
- FV3: 0975bb66
- MOM6: 3ce81f4c
- CICE: 285985c08
- WW3: 96e3f3a8
- FMS: f61416fe
- stochastic_physics: a8e2cc1c8

Co-authored by: Denise Worthen

### CODE REVIEW

**Comment by binli2337** [comment]
@jiandewang, Please add log files to ufs-s2s-model/tests directory.

**Comment by junwang-noaa** [comment]
Jiande, I am committing #176 along with ufs-weather PR#202, the planned date to commit is tomorrow. Can we get that committed first?

**Comment by jiandewang** [comment]
@binli2337 regression log saved to test directory

**Comment by jiandewang** [comment]
@junwang-noaa OK go ahead for your commit, I will re-do mine after yours

**Comment by junwang-noaa** [comment]
Thanks, Jiande.

**Pull request closed without merging**
