### PR TITLE
update WW3 to no longer set an ice value for z0

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
### Description of changes

This updates WW3 so that it no longer sets z0 over ice points 

### Specific notes

In the first round of coupling with WW3 there were two issues noted, the first was that SSTs along coastlines were increasing and the second was temperature over ice had changed significantly.   The coastline issue was resolved by @SMoorthi-emc
PR #161 but this further improves (ie. decreases) the change in the surface temperature over ice. 

Issues Fixed (include github issue #):

- This should close issue #92

Are changes expected to change answers?
- bit for bit (no)
- more substantial (yes)

Specific changes:
- changes in parm directory (no)
- changes in module files (no)
- new tests added or removed (no)

Answers will change for wave tests, new baselines and mod_def input files for WW3 are required. 

Testing performed:
- machines: Orion 
- details: 35 day tests comparing waves to no waves 

Hashes used for testing:
- NEMS: a44b1f7df837cd320d78683717ffd27bcee023d8
- CMEPS: f52f263a7d1c443e3c3f33fa00590f180d068888
- FV3: 0e83a92c2e79e3f2fb5894e41efec12ff34be888
- MOM6: d996f62fc06a3d33ce98943438c8cc84cdacee8c
- CICE: (CICE5) 59e40edc2240724fca2b40531402ff94b2966540
- WW3: 9bc7e8ca67c68a2a1b67bffcc0c122d9a0cb335b
- FMS: f61416fef691d9ba39a40df1ce72aa574f54c390
- stochastic_physics: a8e2cc1c84a1e6a7deb9eef152edec2992b1a859

The 35 day tests were run on orion for Feb and Aug of 2013. 

With waves: 
/work/noaa/marine/jmeixner/p5ww3tests/wwaves/COMROOT/wave_022013/gfs.20130201/00
/work/noaa/marine/jmeixner/p5ww3tests/wwaves/COMROOT/wave_Aug2013/gfs.20130801/00

No waves (for comparison):
/work/noaa/marine/jmeixner/p5ww3tests/nowave/COMROOT/nowave_02213/gfs.20130201/00/
/work/noaa/marine/jmeixner/p5ww3tests/nowave/COMROOT/nowave_082013/gfs.20130801/00/

Plots by @LydiaStefanova-NOAA to show changes in SST and surface temp over ice. 

This is Feb 2013 of surface temp waves minus no waves, day 1 average on left, 35 day average on right 
Screen Shot 2020-08-28 at 3 27 15 PM

This is Aug 2013 of surface temp waves minus no waves, day 1 average on left, 35 day average on right 
Screen Shot 2020-08-28 at 3 28 22 PM

This is Feb 2013 of SST, Day 1 average on Left, Days 1-10 on right: 

Screen Shot 2020-08-28 at 3 30 59 PM

Aug 2013 of SST, Day 1 average on Left, Days 1-10 on right: 
Screen Shot 2020-08-28 at 3 31 38 PM

More analysis can be provided if required.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Related PR for WW3: https://github.com/NOAA-EMC/WW3/pull/248

**Comment by junwang-noaa** [comment]
May I ask what is the status of this PR? Is RT done?

**Comment by JessicaMeixner-NOAA** [comment]
Working on the build script for the WW3 pre/post jobs which needs to be in place for this commit.  Having issues with grib on orion.  Orion baselines have been created but still need ww3_grib to build

**Comment by junwang-noaa** [comment]
If I understand correctly, the s2s model does not run any WW3 pre/post
jobs, is it possible that we can first get ww3 with z0 fix in s2s and have
another commit when ww3 pre/post build issue is fixed? If you prefer to do
them in one commit, may I ask the estimated timeline to get this commit in?
If you need more time, can we get CICE6 PR in s2s? Several other
development work are dependent on that PR.

**Comment by junwang-noaa** [comment]
Jessica, since we do not hear from you about the timeline to get this PR ready, we will go ahead with PR #160. Please let me know if you have questions.

**Comment by JessicaMeixner-NOAA** [comment]
The WW3 pre/post jobs are needed to build the mod_defs for this commit.  I found a sufficient work around for that and have postponed the post build jobs for now.   I'm getting ready to move the orion baseline to the official area and can have the hera/wcoss baselines done this evening.  I hope I can still push this commit.

**Comment by junwang-noaa** [comment]
OK, please go ahead.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa @DeniseWorthen @binli2337  I have the logs for hera and orion pushed.  I messed up the starting point for my baselines somehow with the machine switch for wcoss-dell.  I hope I have that sorted out now and will get them pushed up as soon as they are ready.   To help the CICE6 PR go through as soon as possible after I made baselines on hera for the wave RTs which would have different answers than what Denise is already working on.  I couldn't compile on orion due to a missing library, but when it's there am happy to do the same for Orion and WCOSS (once I finish the ones for this PR).

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for letting us know. May I ask what is the missing library? Will you add it to the s2s module files? If yes, we may need to add it in weather module files too since we are unifying the two repos.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa There are no missing libraries for this PR. For CICE6 PR: https://github.com/ufs-community/ufs-s2s-model/pull/160  that  @DeniseWorthen is working on, for orion esmflocal/8.1.0.27bs is missing.

**Comment by DeniseWorthen** [comment]
On orion, I am using module load esmflocal/8.1.0.27bs.release and module load esmflocal/8.1.0.27bsg.release

I think the "release" will be removed but when I tested yesterday the esmflocal still was using this name.

**Comment by junwang-noaa** [comment]
Yes, the esmf lib convention on orion does not change yet.

**Comment by JessicaMeixner-NOAA** [comment]
So the  cpld_fv3_ccpp_mom6_cice_cmeps_restart  test failed on wcoss-dell with: 

```
[270] forrtl: severe (174): SIGSEGV, segmentation fault occurred
[270] Image              PC                Routine            Line        Source
[270] fcst.exe           0000000002C7A1CD  Unknown               Unknown  Unknown
[270] libpthread-2.17.s  00002B50063F8630  Unknown               Unknown  Unknown
[270] fcst.exe           000000000082B33E  ice_gather_scatte        2103  ice_gather_scatter.F90
[270] fcst.exe           000000000078A722  ice_read_write_mp        1123  ice_read_write.F90
[270] fcst.exe           000000000078D75C  ice_restart_mp_re         459  ice_restart.F90
[270] fcst.exe           0000000000790D5A  ice_restart_drive         319  ice_restart_driver.F90
[270] fcst.exe           0000000000651C2C  cice_initmod_mp_i         205  CICE_InitMod.F90
```

Is this the error that's been previously seen by @binli2337 @DeniseWorthen and others.  I'm assuming this also exists in the current develop branch as there's nothing this PR changes that theoretically should effect this.

**Comment by DeniseWorthen** [comment]
That is definitely the error I got (issue #164). There is some issue on Dell that is intermittent. We need to resolve this if we don't have a method that works consistently (sequential for example).

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA on dell, please do not use ecflow to run RT, try: rt.sh -f

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa it failed for both ecflow and sequential

**Comment by junwang-noaa** [comment]
Let me checkout your PR and give a try

**Comment by JessicaMeixner-NOAA** [comment]
The 5th+ time was the charm, the restart test has passed this time. A few more tests still need to run on dell, but hopefully all will go okay. I'll push the logs up later this evening or in the morning.

**Comment by junwang-noaa** [comment]
The restart test also passed in my RT test. The PR is running very slow, so
far 12 tests have run and they all ran successfully.

**Comment by JessicaMeixner-NOAA** [comment]
Okay, now the debug build is not building from what looks to be a module issue: 
```
Lmod has detected the following error:  Cannot load module "esmf/8.1.0bs21g". At least one of these
module(s) must be loaded:
   Netcdf-parallel

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    esmf/8.1.0bs21g  /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/soft/modulefiles/esmf/8.1.0bs21g
```
I don't appear to have this issue on Mars, just Venus.

**Comment by junwang-noaa** [comment]
It is fixed. I am running RT again too.

**Comment by JessicaMeixner-NOAA** [comment]
All baseline logs have been pushed @junwang-noaa @DeniseWorthen

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Thanks for getting the RT done.

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
